#!/bin/bash -l
runEdm() {
  export EDMOBJECTS=/global/devel/extensions/dgs1/src/edm/setup
  export EDMHELPFILES=/global/devel/extensions/dgs1/src/edm/helpFiles
  export EDMBASE=/global/devel/extensions/dgs1/src/edm
  export EDM=/global/devel/extensions/dgs1/src/edm/edmMain/O.linux-x86/edm
  export EDMPVOBJECTS=/global/devel/extensions/dgs1/src/edm/setup
  export EDMFILES=/global/devel/systems/helios/edm_h054/edm/setup
  export EDMDATAFILES=$EDMDATAFILES:/global/devel/systems/helios/edm/screens
  export EDMDATAFILES=$EDMDATAFILES:/global/devel/systems/edm/screens
  export EDMSCRIPTS=/global/devel/systems/helios/edm/scripts
  $EDM HELIOSMain.edl &
  echo "Edits are possible in this mode."
}
runEdm
