 
ROOTINC = $(shell root-config --cflags)
ROOTLIB = $(shell root-config --libs)

CCFLAG   = -I. $(ROOTINC) $(ROOTLIB)
ccFLAG	 = -I. $(ROOTINC) $(ROOTLIB)
CC       = g++ -m32 -DLINUX $(CCENV) -D_FILE_OFFSET_BITS=64 -DMAC=0
cc       = gcc -m32 -DLINUX $(CCENV) -D_FILE_OFFSET_BITS=64 -DMAC=0


TRAILOR  = -lm
FF       = f77 -m32 -fbounds-check

SOCKET = 
NSL = -lnsl

