#!/bin/bash

if [ $# -eq 0 ] || [ $# -eq 1 ] || [ $1 == "-help"  ]; then
  echo "$./process_MultiRuns [RunNum1] [RunNum2] [EventBuild] [SaveTrace]"
  echo "    RunNum1 = start run number"
  echo "    RunNum2 = stop run number"
  echo "   EventBld = n/1/0*   || n>1 = with Trace"  
  echo "  SaveTrace = 0/1      "
  echo "        * negative option = force "
  exit 1
fi;

source ${HELIOSSYS}/digios/analysis/Armory/process_PathSetting

RUN1=$1
RUN2=$2

isBuild=1
isSaveTrace=0

if [ $# -ge 3 ]; then isBuild=$3; fi
if [ $# -ge 4 ]; then isSaveTrace=$4; fi


if [ "${RUN1:0:1}" == "0" ]; then
    RUN1=${RUN1:1:2}
elif [ "${RUN1:0:2}" == "00" ]; then
    RUN1=${RUN1:2:1}
else
    RUN1=$(printf '%d' $RUN1)
fi

#if RUN2 == -1, find the last runID from daq.
if [ ${RUN2} -eq -1 ]; then
  IP=192.168.1.2
  rsync -avuht --progress "helios@${IP}:${daqDir}/expName.sh" ${AnalysisDir}/../.
  source ../../expName.sh #load expName and last RUN
  RUN2=$LastRunNum
  echo "---- Last run is $RUN2"
fi

if [ "${RUN2:0:1}" == "0" ]; then
    RUN2=${RUN2:1:2}
elif [ "${RUN2:0:2}" == "00" ]; then
    RUN2=${RUN2:2:1}
else
    RUN2=$(printf '%d' $RUN2)
fi

runID1=$(printf '%03d' $RUN1)
runID2=$(printf '%03d' $RUN2)

echo -e "\033[1;31m"
echo "============================================================================="
echo "============================== RUN $runID1 to $runID2 ==============================="
echo -e "=============================================================================\033[0m"
echo " EventBuild      : ${isBuild}"
echo " SaveTrace       : ${isSaveTrace}"
echo "============================================================================="


for iRUN in $(seq ${RUN1} ${RUN2}); do

    runID=$(printf '%03d' $iRUN)

    echo -e "\033[1;34m"
    echo "============================================================================="
    echo "============================ RUN $runID ========================================"
    echo "============================================================================="
    echo -e "\033[0m"

    #######################################
    ####################  Download raw data
    ../Armory/process_Download $iRUN

    #######################################
    #################### Sort and GeneralSort
    ../Armory/process_Sort $iRUN $isBuild $isSaveTrace

done

#root -l ../Armory/runsCheck.C  #check the run Entries, and duration

exit 1
