#!/bin/bash

if [ $# -eq 0 ] || [ $# -eq 1 ] || [ $1 == "-help"  ]; then
  echo "$process_Slurm [RunNum1] [RunNum2] [time] [Merge] [EventBuild] [GeneralSort]"
  echo "    RunNum1  = start run number"
  echo "    RunNum2  = stop run number"
  echo "       time  = Allocate time, e.g. 01:00:00"
  echo "      Merge* =   1/0     "  
  echo "   EventBld* = 2/1/0   || 2 = with Trace"  
  echo " GenralSort* = n/1/0   || 1 = GeneralSort.C, n = GeneralSortTraceProof.C with n-worker"
  echo "        * negative option = force "
  exit 1
fi;

dir=$(pwd)
cd ../../
source heliosrc.sh
cd $dir
source ../Armory/process_PathSetting

RUN1=$1
RUN2=$2
time=$3

isMerge=1
isBuild=1
isGeneralSort=1
mergeStr="M"
buildStr="B"
sortStr="S"

if [ $# -ge 4 ]; then isMerge=$4; fi
if [ $# -ge 5 ]; then isBuild=$5; fi
if [ $# -ge 6 ]; then isGeneralSort=$6; fi

if [ $isMerge -eq 0 ]; then mergeStr="0"; fi
if [ $isBuild -eq 0 ]; then buildStr="0"; fi
if [ $isGeneralSort -eq 0 ]; then sortStr="0"; fi

if [ "${RUN1:0:1}" == "0" ]; then
    RUN1=${RUN1:1:2}
elif [ "${RUN1:0:2}" == "00" ]; then
    RUN1=${RUN1:2:1}
else
    RUN1=$(printf '%d' $RUN1)
fi

if [ "${RUN2:0:1}" == "0" ]; then
    RUN2=${RUN2:1:2}
elif [ "${RUN2:0:2}" == "00" ]; then
    RUN2=${RUN2:2:1}
else
    RUN2=$(printf '%d' $RUN2)
fi

runID1=$(printf '%03d' $RUN1)
runID2=$(printf '%03d' $RUN2)

echo "================================================"
echo "=======  Slurm-job RUN $runID1 to $runID2 ================"
echo "================================================"
echo "Merge       : ${isMerge}"
echo "Build       : ${isBuild}  ${GEBSortMsg}"  
echo "GeneralSort : ${isGeneralSort} ${GeneralSortMsg}"
echo "============================================="

if [ $isMerge -eq 0 ] && [ $isBuild -eq 0 ] && [ $isGeneralSort -eq 0 ]; then
    echo "nothing to do. exit."
    exit 1
fi

slurmFile=slurm.sh

name=${mergeStr}${buildStr}${sortStr}

core=36
if [ $isMerge -ne 0 ]; then core=1; fi
if [ $isBuild -ne 0 ]; then core=1; fi
if [ $isGeneralSort -ne 0 ]; then core=36; fi

logFile="slurm-${expName}_${name}_${runID1}-${runID2}.out"

echo "#!/bin/bash" > $slurmFile

echo "#SBATCH --job-name=${name}" >> $slurmFile
echo "#SBATCH --account=HELIOS" >> $slurmFile
echo "#SBATCH --partition=bdwall" >> $slurmFile
echo "#SBATCH --node=1" >> $slurmFile
echo "#SBATCH --ntasks-per-node=${core}" >> $slurmFile
echo "#SBATCH --time=${time}" >> $slurmFile
echo "#SBATCH --output=${logFile}" >> $slurmFile
echo "" >> $slurmFile
echo 'echo "===================="' >> $slurmFile
echo 'echo hostname = $(hostname)' >> $slurmFile
echo 'echo "===================="' >> $slurmFile
echo "" >> $slurmFile
if [ $isMerge -ne 0 ]; then
    echo 'echo "==================================="' >> $slurmFile
    echo 'cat GEBMerge.chat' >> $slurmFile
fi

if [ $isBuild -ne 0 ]; then
    echo 'echo "==================================="' >> $slurmFile
    echo 'cat GEBSort.chat' >> $slurmFile
fi
echo 'echo "==================================="' >> $slurmFile

echo "process_MultiRuns $RUN1 $RUN2 $isMerge $isBuild $isGeneralSort" >> $slurmFile

sbatch $slurmFile

squeue -u $(whoami) -l

lcrc-sbank -q balance
