#!/bin/bash

if [ $# -eq 0 ] || [ $1 == "-help"  ]; then
  echo "$./process_run [RunNum] [EventBuild] [Sort] [Monitor]"
  echo "     RunNum = run number / \"lastRun\" "
  echo " EventBuild = 0/1/2         ||  0 = no EventBld, 1 = EventBld, 2 = EventBld with trace"
  echo "       Sort = n/1/0/-1/-n   || 1 = GeneralSort.C, n = GeneralSortTraceProof.C with n-worker"
  echo "   Monitors = 2/1/0         || 1 = single run,  2 = using the list in ChainMonitors.C"
  echo "                              10 = single run and post to websrv, 20 = list runs and post to websrv"
  echo ""
  echo "       **** When feeding trace data to Monitors, the EventBld flag must be 2 or -2."
  echo ""
  exit 1
fi;

RUN=$1

isBuild=0
isGeneralSort=0
isMonitor=0

traceFlag=false

if [ $# -ge 2 ]; then isBuild=$2; fi
if [ $# -ge 3 ]; then isGeneralSort=$3; fi
if [ $# -ge 4 ]; then isMonitor=$4; OverRideMonitor="" ; fi

if [ $# -eq 1 ]; then
  isBuild=1
  isGeneralSort=1
  isMonitor=1
fi

GeneralSortMsg="no trace"

if [ ${isGeneralSort} -ge 2 ] || [ ${isGeneralSort} -le -2 ]; then
  isTrace=1
  GeneralSortMsg="trace with ${isGeneralSort} core"
  traceFlag=true
fi

if [ "${RUN}" == "lastRun" ]; then 
  source ../Armory/process_PathSetting
  IP=192.168.1.2
  rsync -avuht --progress "helios@${IP}:${daqDir}/expName.sh" ${AnalysisDir}/../.
  RUN=${LastRunNum}
fi

#remove any zero
if [ "${RUN:0:2}" == "00" ]; then
    RUN=${RUN:2:1}
elif [ "${RUN:0:1}" == "0" ]; then
    RUN=${RUN:1:2}
else
    RUN=$(printf '%d' $RUN)
fi

runID=$(printf '%03d' $RUN)

echo "============================================="
echo "============ RUN $runID ========================"
echo "============================================="

echo "GeneralSort : ${isGeneralSort} ${GeneralSortMsg}"
echo "isMonitor   : ${isMonitor} ${OverRideMonitor}"
echo "============================================="


if [ ${isGeneralSort} -ne -1 ] || [ ${isGeneralSort} -ne 1 ]; then
 echo -e "\033[1;31m##########################################################\033[0m"
 echo -e "\033[1;33m Please check GeneralSortTraceProof.C to enable detectors \033[0m"
 echo -e "\033[1;31m##########################################################\033[0m"
fi

#######################################
####################  Download raw data
../Armory/process_Download $RUN

#######################################
#################### EventBuild and GeneralSort
../Armory/process_Sort $RUN $isBuild $isGeneralSort 

########################################
#################### Monitor

if [ $isMonitor -eq 1 ] ; then
  root -l "ChainMonitors.C($RUN, -1, false, ${traceFlag})" # single run
elif [ $isMonitor -eq 2 ] ; then
  root -l "ChainMonitors.C(-1,-1, false, ${traceFlag})"  #all runs listed 
elif [ $isMonitor -eq 20 ] ; then
  root -l "ChainMonitors.C(-1,-1, true, ${traceFlag})"
elif [ $isMonitor -eq 10 ] ; then
  root -l "ChainMonitors.C(${RUN},-1, true, ${traceFlag})"  
fi  

  
exit 1
