#!/bin/bash

if [ $# -lt 3 ] || [ $1 == "-help"  ]; then
  echo "$./process_Sort [RunNum] [EventBuild] [GeneralSort]"
  echo "    RunNum  = run number"
  echo " EventBuild = 0/1/2       ||  0 = no EventBld, 1 = EventBld, 2 = EventBld with trace"
  echo " GenralSort = n/2/1/0/neg ||  1 = GeneralSort.C, 2 = GeneralSortTrace.C, n = GeneralSortTraceProof.C with n-worker"
  echo "                       |"
  echo "                       +---- negative for force"
  exit 1
fi;

source ${HELIOSSYS}/analysis/Armory/process_PathSetting

RUN=$1
runID=$1
isBuild=$2
isGeneralSort=$3
isTrace=0

if [ ${isGeneralSort} -ge 2 ] || [ ${isGeneralSort} -le -2 ] ; then
  isTrace=1
fi

if [ ${isBuild} -ge 2 ] || [ ${isBuild} -le -2 ] ; then
  isTrace=1
fi

#just in case people put %03d as RUN
if [ "${RUN:0:2}" == "00" ]; then
    RUN=${RUN:2:1}
elif [ "${RUN:0:1}" == "0" ]; then
    RUN=${RUN:1:2}
else
    RUN=$(printf '%d' $RUN)
fi

RUN=$(printf '%03d' ${RUN})

if [ $# -eq 1 ]; then
    echo -e "${Cyan}============================================="
    echo "============ RUN $RUN ========================"
    echo -e "=============================================${NC}"
fi

source $ROOTSYS/bin/thisroot.sh

#######################################
#################### Sort
echo -e "${RED}######################### EventBuilder started sorting run $RUN${NC}"

if [ $isBuild -eq 0 ]; then 
    echo -e "${YELLOW} >>>>>> skipped by user${NC}" 
elif [ $isBuild -gt 0 ]; then

    #==== check raw data timeStamp
    if [ ${Arch} == "Linux" ]; then
        if [ ${PCName} == "digios1" ]; then
            echo -e "\033[0;31m WARNING : MAXIMUM MERGE SIZE IS 4.0GB \033[0m."
        fi
        rawDataTime=`stat -c "%Z"  ${DATADIR}/${expName}_run_$RUN.gtd* | sort -rn | head -1`    
    else
        rawDataTime=`stat -f "%Sm" -t "%Y%m%d%H%M%S" ${DATADIR}/${expName}_run_$RUN.gtd* | sort -rn | head -1`    
    fi

    #==== check if root data exist
    isRootDataExist=`ls -1 ${ROOTDIR}/run${RUN}.root 2>/dev/null | wc -l`    
    if [ ${isRootDataExist} -gt 0 ]; then
        if [ ${Arch} == "Linux" ]; then
            rootDataTime=`stat -c "%Z" ${ROOTDIR}/run${RUN}.root`
        else
            rootDataTime=`stat -f "%Sm" -t "%Y%m%d%H%M%S" ${ROOTDIR}/run${RUN}.root`
        fi
    else
        rootDataTime=0
    fi

    if [ ${rawDataTime} -ge ${rootDataTime} ]; then
        echo -e "${RED}=================== RUN $RUN: EventBuilder started at `date`${NC}"
        
        ${GEBDIR}/EventBuilder ${ROOTDIR}/run${RUN}.root 1000 $isTrace `\ls -1 ${DATADIR}/${expName}_run_$RUN.gtd*`

        echo -e "${RED}====================== RUN $RUN: EventBuilder DONE at `date`${NC}"
        echo -e "saved root file >>>>>>  ${YELLOW} ${ROOTDIR}/run${RUN}.root ${NC} "
        echo "=================================================================="
    else
        echo -e "${BLUE}Root data are newer than raw data. No need to do again.${NC}"
        echo -e "${GREEN}You can Force event buidling using option -1, ${ORANGE} see ./process_run.sh -help${NC}"
    fi
elif [ $isBuild -lt 0 ]; then # force Sort
    echo -e "${RED}=================== RUN $RUN: EventBuilder started at `date`${NC}"
    echo -e "${YELLOW} >>>>>>>>>>>>> force sort by user ${NC}"
    
    ${GEBDIR}/EventBuilder ${ROOTDIR}/run${RUN}.root 1000 $isTrace `\ls -1 ${DATADIR}/${expName}_run_$RUN.gtd*`
    
    echo -e "${RED}====================== RUN $RUN: EventBuilder DONE at `date`${NC}"
    echo -e "saved root file >>>>>>  ${YELLOW} ${ROOTDIR}/run${RUN}.root ${NC} "
    echo "=================================================================="
fi

########################################
#################### Process_run.C, GeneralSort

#---------- check gen_run date
echo -e "${RED}######################### GeneralSort started for run $RUN${NC}"

if [ $isGeneralSort -eq 0 ]; then 
    echo -e "${YELLOW} >>>>>> skipped by user${NC}" 

elif [ $isGeneralSort -gt 0 ]; then
    
    isRootDataExist=`ls -1 ${ROOTDIR}/run${RUN}.root 2>/dev/null | wc -l`

    if [ $isRootDataExist -eq 0 ]; then
        
        echo "====== ${ROOTDIR}/run${RUN}.root does not exist."
        
    else
        #==== check run###.root timeStamp
        if [ ${Arch} == "Linux" ]; then
            rootTime=`stat -c "%Z" ${ROOTDIR}/run${RUN}.root | sort -rn | head -1`
        else
            rootTime=`stat -f "%Sm" -t "%Y%m%d%H%M%S" ${ROOTDIR}/run${RUN}.root | sort -rn | head -1`
        fi

        ls -lh  ${ROOTDIR}/run${RUN}.root

        #==== check gen_run###.root timeStamp
        isGenRootDataExist=`ls -1 ${ROOTDIR}/gen_run${RUN}.root 2>/dev/null | wc -l`

        if [ $isGenRootDataExist -gt 0 ]; then
            if [ ${Arch} == "Linux" ]; then
                genRootTime=`stat -c "%Z" ${ROOTDIR}/gen_run${RUN}.root | sort -rn | head -1`
            else
                genRootTime=`stat -f "%Sm" -t "%Y%m%d%H%M%S" ${ROOTDIR}/gen_run${RUN}.root | sort -rn | head -1`
            fi
        else
            genRootTime=0
        fi 

        if [ $rootTime -ge $genRootTime ]; then

            if [ $isGeneralSort -eq 1 ]; then
                echo -e "${RED}######################### GeneralSort.C${NC}"
            elif [ $isGeneralSort -gt 1 ]; then
                echo -e "${RED}######################### GeneralSortTraceProof.C${NC}"
                mkdir ~/.proof/working
                cp ../working/GeneralSortMapping.h ~/.proof/working/.
            fi
            root -l -q -b "../Armory/process_run.C(${runID}, ${isGeneralSort})"

        else
            echo -e "${BLUE}gen_run${RUN}.root are newer than run${RUN}.root. No need to sort again.${NC}"
            echo -e "${GREEN}You can Force sorting using option -1, ${ORANGE} see ./process_run.sh -help${NC}"
        fi

    fi

elif [ ${isGeneralSort} -lt 0 ]; then 

    ls -lh  ${ROOTDIR}/run${RUN}.root

    echo -e "${YELLOW} >>>>>> forced by user ${NC}"
    if [ $isGeneralSort -eq -1 ]; then
        echo -e "${RED}######################### GeneralSort.C${NC}"
    elif [ $isGeneralSort -lt -1 ]; then
        echo -e "${RED}######################### GeneralSortTraceProof.C${NC}"
        mkdir ~/.proof/working
        cp ../working/GeneralSortMapping.h ~/.proof/working/.
    fi
    \root -l -t -q -b "../Armory/process_run.C(${runID}, ${isGeneralSort})"
fi

