#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

source ${HELIOSSYS}/expName.sh
RUN=${LastRunNum}
datalocation=${daqDataPath}/${expName}/data
currentLocation=$(pwd)
echo -e "    ExpName = ${YELLOW} ${expName} ${NC}"
echo "###################################"

stopFlag=0
count=0
sleepTime=60 #second

while [ $stopFlag -eq 0 ]; do

    echo "###########################################"
    echo $(date) " | Run" ${RUN} " | time:" $count " min < " $stopCount " min"	

    count=$((count+1))

    mod=$(( $count % 5 ))
    if [ $mod -eq 0 ]; then
	echo "tell Mac to run ./process_run"
	xterm -T  ${HELIOSSYS}/daq/edm/scripts/AutoMonitor -e "ssh heliosdigios@192.168.1.193 AutoProcess "${RUN}"" &

	echo "ahahah"
    fi
    
    #echo "method:" $method "|" $(date) "|" $sleepTime "|" $count
    sleep $sleepTime
    
done