#!/bin/bash

if [ $# -ne 2 ] && [ $# -ne 3 ] ; then
    echo "AutoStartStop  time  [min_int]        [repeatition_int]"
    echo "AutoStartStop  size  [kilo-byte_int]  [repeatition_int]"
    echo "****** if no repeatation, or repeatation = 0 or 1 or  < -1, only do once. "
    echo "       if repeatation = -1, infinity"
    echo "****** 3 min is a special run that change the recoil trigger (Y-trigger) on"
    exit
fi

method=$1

if [ $# -ge 3 ]; then
    repeat=$3
else
    repeat=1
fi

if [ $repeat -gt 1 ] || [ $repeat -eq -1 ] ; then
    msg1="Start & Stop"
else
    msg1="Stop"
fi


if [ $method == "time" ]; then
    stopCount=$2
    printTime=$((${stopCount} / 3 + 1)) 

    if [ $printTime -lt 10 ]; then
	printTime=10
    fi

    echo "##########################################################"
    echo "   Auto $msg1 for ${stopCount} min, print for ${printTime} min "
    echo "##########################################################"

    if [ $stopCount == 3 ]; then
	caput VME32:MTRG:SUM_Y on
	echo "===================== 3 mins recoil trigger run "
    fi

elif [ $method == "size" ]; then
    maxSize=$2
    echo "###################################"
    echo "   Auto $msg1 for ${maxSize} byte           "
    echo "###################################"
else
    echo "Time or FileSize !!!"
    echo "AutoStartStop  time  [min_int]"
    echo "AutoStartStop  size  [kilo-byte_int]"
    exit
fi

#=========== Check DAQ is saving
#isDAQSaving=$(caget Online_CS_SaveData | awk '{print $2}')
#if [ $isDAQSaving == "Save" ]; then
#    echo -e "\033[33m !!!!!! it seem that the DAQ is saving. Please fix that or call Ryan!!!! \033[m"
#    exit
#fi

#if [ $repeat -eq -1 ] ;then
#    echo -e "\033[1;33m !!!!! infinite runs !!!!! \033[m"
#fi

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

source ${HELIOSSYS}/expName.sh
RUN=${LastRunNum}
datalocation=${daqDataPath}/${expName}/data
currentLocation=$(pwd)
echo -e "    ExpName = ${YELLOW} ${expName} ${NC}"
echo "###################################"

stopFlag=0
sleepTime=60
count=0

firstRunNum=$((${LastRunNum} + 1))
#firstRunNum=$((${LastRunNum}))

echo "first Run : ${firstRunNum}"

#===== Check is the Run was started, if not, start
isStarted=$(caget Online_CS_StartStop | awk '{print $2}')
if [ $isStarted == "Stop" ]; then
    cd ${datalocation}
    
    echo "===================== Auto-Start-Stop script"

    if [ $stopCount == 3 ]; then
	COMMENT="beam check"
#    else
#	echo "Crtl+C to cancel with no harm"
#	echo "Please type Single-line comment:"
#	read -p '>>' COMMENT
    fi

    source ${HELIOSSYS}/daq/edm/scripts/start_run.sh "Auto Start for $repeat times, $stopCount min each. ${COMMENT}"
    stopFlag=0
    cd ${currentLocation}
    source ${HELIOSSYS}/expName.sh
    RUN=${LastRunNum}
else
    echo "======= Please stop the ACQ, or stop the run, and start again ========"
    exit
fi

while [  $stopFlag -eq 0 ]; do  

    if [ $method == "size" ]; then
	size=$(du -c --time ${HELIOSSYS}/analysis/data/${expName}_run_*$RUN* | tail -1 | awk '{print $1}')

	if [ $size -gt $maxSize ]; then
	    stopFlag=1
	    echo $(date) " | Run" ${RUN} " | size:" $size " kB >= " $maxSize " kB ====> Stop!!!"	
	    source ${HELIOSSYS}/daq/edm/scripts/stop_run.sh "Auto stop after ${maxSize} kB"
	    
	    if [ $repeat -gt 1 ] || [ $reapet -eq -1 ] ; then
		echo "################ wait for 10 sec before next run"
		echo -e "######## ${YELLOW}CHANCE TO STOP the auto!!!!${NC}"
		echo "========== number of repeat : ${repeat}"
		sleep 10
		cd ${datalocation}
		source ${HELIOSSYS}/daq/edm/scripts/start_run.sh "Auto start! $repeat"
		stopFlag=0
		cd ${currentLocation}
		source ${HELIOSSYS}/expName.sh
		RUN=${LastRunNum}
		if [ $repeat -gt 1 ] ; then
		    repeat=$((repeat-1))
		fi
		#echo $(date) " | Run" ${RUN} " | size:" $size " kB < " $maxSize " kB"
	    fi
	fi    
	echo $(date) " | Run" ${RUN} " | size:" $size " kB < " $maxSize " kB"
	
    fi

    #========================= For time 
    if [ $method == "time" ]; then
	
	if [ $count -eq $stopCount ]; then 
	    stopFlag=1
	    echo $(date) " | Run" ${RUN} " | time:" $count " min >= " $stopCount " min ====> Stop!!!"	

	    echo "tell Mac to run AutoProcess_run firstRun:${firstRunNum} ${RUN}"
	    xterm -T AutoProcess -e "ssh heliosdigios@192.168.1.164 /Users/heliosdigios/digios/AutoProcess "${firstRunNum}" "${RUN}" 1" &

	    source ${HELIOSSYS}/daq/edm/scripts/stop_run.sh "Auto stop after $count mins"

#	    if [ $stopCount -eq 3 ]; then
#		caput VME32:MTRG:SUM_Y off
#	    fi

	    if [ $repeat -gt 1 ] || [ $repeat -eq -1 ]; then
		echo "################# wait for 10 sec before next run"
		echo -e "######## ${RED}CHANCE TO STOP the auto!!!! Ctrl+C to stop.${NC}"
		echo "========== number of repeat : ${repeat}"
		sleep 10
		#if [ $expname == "h078_14C14N" ]; then
		#    caput VME01:MDIG1:trigger_mux_select IntAcptAll
		#fi
		cd ${datalocation}
		source ${HELIOSSYS}/daq/edm/scripts/start_run.sh "Auto start! $repeat"
		cd ${currentLocation}
		stopFlag=0
		count=0
		source ${HELIOSSYS}/expName.sh
		RUN=${LastRunNum}
		if [ $repeat -gt 1 ]; then
		    repeat=$((repeat-1))
		fi
                #echo $(date) " | Run" ${RUN} " | time:" $count " min < " $stopCount " min"	
	    fi
	fi
	 
	echo $(date) " | Run" ${RUN} " | time:" $count " min < " $stopCount " min"	
	count=$((${count}+1))

	mod=$(( $count % ${printTime} ))
	if [ $mod -eq 0 ]; then
	    echo "tell Mac to run AutoProcess_run firstRun:${firstRunNum} ${RUN}"
	    xterm -T AutoProcess -e "ssh heliosdigios@192.168.1.164 /Users/heliosdigios/digios/AutoProcess "${firstRunNum}" "${RUN}" 0" &
	fi

    fi

    if [ $stopFlag -eq 1 ]; then
	echo "########################## Auto Start/Stop Ended."
    else
        #echo "method:" $method "|" $(date) "|" $sleepTime "|" $count
	sleep $sleepTime
    fi
done

