#!/bin/bash

VME=$1
DIG=$2

IP="heliosDB.onenet"
database="testing"

echo "------ Database for VME0${VME}:DIG${DIG} ----"

CH="0 1 2 3 4 5 6 7 8 9"

loopflag=1

while [ ${loopflag} -eq 1 ]; do

   for c in $CH ; do

	hitRate=$(caget VME0${VME}:MDIG${DIG}:disc_count${c}_RBV | awk '{print $2}')

	clear
	#echo "==========================="
	echo "Database for VME0${VME}:DIG${DIG}:CH${c} ---- HitRate:${hitRate}"
	
	#dataStr="INSERT hitRate,VME=${VME},DIG=${DIG},CH=${c} value=${hitRate}"
        #echo ${dataStr}   
	#influx -execute "${dataStr}" -database="testing"

	dataStr="hitRate,VME=${VME},DIG=${DIG},CH=${c} value=${hitRate}"
	#echo "------"$dataStr
	curl -sS -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1
	echo "Although operation time-out, the data is OK."
	#sleep 0.5
	
   done

   sleep 3

done