#!/bin/bash

IP="heliosDB.onenet"
database="testing"

echo "------ Database for VME0${VME}:DIG${DIG} ----"

VME="1 2 3 4"

loopflag=1

lastBuff=400

while [ ${loopflag} -eq 1 ]; do

   for c in $VME ; do

	buffer=$(caget DAQC${c}_CV_BuffersAvail | awk '{print $2}')
        #if [ ${c} -eq 1 ]; then
	#    x=$RANDOM
	#    buffer=$(python -c "print (int)($x/32767.*500)")
	#fi
	clear
	#echo "==========================="
	echo "Database for VME${c} ---- Buffer:${buffer}"

	dataStr="buffer,VME=${c} value=${buffer}"
	#echo "------"$dataStr
	curl -v -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1
	
	sleep 0.5

	if [ ${buffer} -lt 200 ]; then
	    caput Online_CS_StartStop Stop
	    sleep 10
	    caput Online_CS_StartStop Start
	fi
   done

done