#!/bin/bash

if [ $# -eq 0 ] || ([ $1 != "start" ] && [ $1 != "stop" ]); then
    echo "Usage: ./helios_database start/stop"
    exit 1
fi

echo "###################################"
echo "    $1  database for Grafana     "
echo "###################################"

option=$1

if [ ${option} == "start" ]; then

xterm -T database1 -geometry 80x40+0+0 -e "~/digios/daq/edm/scripts/DataBase.py" & 

fi


if [ ${option} == "stop" ]; then
    for a in {1..2} ; do 
	processID=$(ps aux | grep database$a | grep 'xterm' | awk '{print $2}')
	kill -9 ${processID}
    done        
fi
