#!/bin/bash

if [ $# -eq 0 ] || ([ $1 != "start" ] && [ $1 != "stop" ]); then
    echo "Usage: ./helios_database start/stop"
    exit 1
fi

echo "###################################"
echo "    $1  database for Grafana     "
echo "###################################"

option=$1

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if [ ${option} == "start" ]; then

    #check is there any database script is running
    isDataBaseRunning=$(ps aux | grep database | grep 'xterm' | wc -l)
    if [ ${isDataBaseRunning} -eq 1 ]; then 
	echo -e "${YELLOW}!!!!!!!!!!!${RED}Helios_Database is already running${YELLOW}!!!!!!!!!!${NC}"
    else
	xterm -T database -geometry 80x40+0+0 -e "~/digios/daq/edm/scripts/DataBase.py" &
    fi

fi


if [ ${option} == "stop" ]; then
     
    processID=$(ps aux | grep database | grep 'xterm' | awk '{print $2}')
    kill -9 ${processID}
         
fi
