#!/bin/bash

if [ $# -eq 0 ] || [ $# -lt 2  ]; then
    echo "Please input VME, DIG and CH"
    echo "         or  array(e.g. BB), Energy/XF/XN/Ring"
    exit 1
fi

IP="heliosDB.onenet"
database="testing"

VME=$1
DIG=$2
CH=$3

re='^[0-9]+$'

if ! [[ $1 =~ $re ]]; then

    if [ ${VME} = "TT" ]; then
	VME=2
	iDIG=3	
    fi
    if [ ${VME} = "TL" ]; then
	VME=2
	iDIG=1	
    fi
    if [ ${VME} = "TR" ]; then
	VME=3
	iDIG=1	
    fi
    if [ ${VME} = "BR" ]; then
	VME=3
	iDIG=3	
    fi
    if [ ${VME} = "BB" ]; then
	VME=4
	iDIG=1	
    fi
    if [ ${VME} = "BL" ]; then
	VME=4
	iDIG=3	
    fi

    if [ $# -eq 3 ]; then

	echo " Set threshold values for array-$1 ${DIG} to $3"

	if [ ${DIG} = "Energy" ]; then
	    CHLIST="0 1 2 3 4"
	fi

	if [ ${DIG} = "XF" ]; then
	    iDIG=$((iDIG+1))
	    CHLIST="0 1 2 3 4"
	fi
	if [ ${DIG} = "XN" ]; then
	    iDIG=$((iDIG+1))
	    CHLIST="5 6 7 8 9"
	fi
	if [ ${DIG} = "Ring" ]; then
	    CHLIST="5 6 7 8 9"
	fi


	for CH in $CHLIST
	do
	    caput VME0${VME}:MDIG${iDIG}:led_threshold${CH} $3		
	done
    fi



    if [ $# -eq 2 ]; then
	CHLIST="0 1 2 3 4 5 6 7 8 9"
	echo " Set threshold values for array-$1 to $2"
	for CH in $CHLIST
	do
	    caput VME0${VME}:MDIG${iDIG}:led_threshold${CH} $2
	done
	iDIG=$(($iDIG+1))
	for CH in $CHLIST
	do
	    caput VME0${VME}:MDIG${iDIG}:led_threshold${CH} $2	
	done
    fi
	

else

    echo " Set Threshold values for VME-${VME}:${DIG}:CH${CH}"

    threshold=$(caget VME0${VME}:MDIG${DIG}:led_threshold${CH} | awk '{print $2}')
    #dataStr="INSERT threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${threshold}"
    #influx -execute "${dataStr}" -database="testing"

    dataStr="threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${threshold}"
    curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1

    echo " === current threshold is ${threshold}"

    read -p " === Set threshold to ? " newThreshold

    caput VME0${VME}:MDIG${DIG}:led_threshold${CH} ${newThreshold}

    #dataStr="INSERT threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${newThreshold}"
    #influx -execute "${dataStr}" -database="testing"

    dataStr="threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${newThreshold}"
    curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1

fi

echo "========= done."