#!/bin/bash

if [ $# -eq 0 ] || [ $# -ne 3  ]; then
    echo "Please input VME, DIG and CH"
    exit 1
fi

IP="heliosDB.onenet"
database="testing"

VME=$1
DIG=$2
CH=$3

echo " Set Thredhold values for VME-${VME}:${DIG}:CH${CH}"

threshold=$(caget VME0${VME}:MDIG${DIG}:led_threshold${CH} | awk '{print $2}')
#dataStr="INSERT threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${threshold}"
#influx -execute "${dataStr}" -database="testing"

dataStr="threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${threshold}"
curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1

echo " === current threshold is ${threshold}"

read -p " === Set threshold to ? " newThreshold

caput VME0${VME}:MDIG${DIG}:led_threshold${CH} ${newThreshold}

#dataStr="INSERT threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${newThreshold}"
#influx -execute "${dataStr}" -database="testing"

dataStr="threshold,VME=${VME},DIG=${DIG},CH=${CH} value=${newThreshold}"
curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1

echo "========= done."