#!/bin/bash

IP="heliosDB.onenet"
database="testing"


echo "------ Database for VME0${VME}:DIG${DIG} ----"

VME="1 2 3 4"

loopflag=1

lastBuff=400

while [ ${loopflag} -eq 1 ]; do

    clear 
    source ~/digios/expName.sh
    RUN=${LastRunNum}
    dataStr="RunNum value=${RUN}"
    curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1
   
    runLen=${#RUN}
    if [ ${runLen} -eq 1 ]; then
	RUN="00"${RUN}
    elif [ ${runLen} -eq 2 ]; then
	RUN="0"${RUN}
    fi;

    fileSize=$(du -c ~/digios/analysis/data/${expName}_run_${RUN}* | tail -1 | awk '{print $1}')
    dataStr="fileSize value=${fileSize}"
    curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1
    echo "Current Run = ${RUN}, FileSize = ${fileSize} Byte"

   for c in $VME ; do

	buffer=$(caget DAQC${c}_CV_BuffersAvail | awk '{print $2}')
	sumHitX=$(caget VME32:MTRG:RAW_TRIG_RATE_COUNTER_2_RBV | awk '{print $2}')
	sumHitY=$(caget VME32:MTRG:RAW_TRIG_RATE_COUNTER_3_RBV | awk '{print $2}')
	
	echo "Database for VME${c} ---- Buffer:${buffer}"
	echo "sumHitX = ${sumHitX}, sumHitY = ${sumHitY}"
	
	dataStr="buffer,VME=${c} value=${buffer}"
	curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1
	dataStr="sumHitX value=${sumHitX}"
	curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1
	dataStr="sumHitY value=${sumHitY}"
	curl -s -XPOST "http://${IP}:8086/write?db=${database}" --data-binary "${dataStr}" --max-time 1 --connect-timeout 1
	

	sleep 0.5

	if [ ${buffer} -lt 300 ]; then
	    caput Online_CS_StartStop Stop
	    echo " stop ACQ at $(date), wait for 10 sec" >> ~/helioBuffer.log
	    sleep 10
	    caput Online_CS_StartStop Start
	    echo "start ACQ at $(date)" >> ~/helioBuffer.log
	fi
   done

done