#!/bin/bash -l

# Setup all digitizer delay windows M, K, D, D2
# also setup raw data length, data window, peak sensitivity
#  LEd threshold, channel enable, discriminator mode
# trigger mode, edge select, pileup mode, extension mode,
# extension enable, trigger configuration and time windows

cd /global/devel/systems/edm/scripts

echo "Mass setting of Digitizers to default operational values"
#/global/devel/systems/edm/scripts/set_dig_all baseline_delay 260   # do this before setting d,k,m,d2

caput GLBL:DIG:baseline_start 1000 

/global/devel/systems/edm/scripts/set_dig_all counter_mode 0 > null     # this allows the scalers to count

caput GLBL:DIG:delay 26
caput GLBL:DIG:win_comp_min -8
caput GLBL:DIG:win_comp_max -4
caput GLBL:DIG:disc_width 15

caput GLBL:DIG:led_threshold 50
caput GLBL:DIG:raw_data_length 1.0
caput GLBL:DIG:raw_data_window 0.32
caput GLBL:DIG:d_window 0.20
caput GLBL:DIG:k_window 0.80
caput GLBL:DIG:d3_window 0.20
#caput GLBL:DIG:d_window 0.60
#caput GLBL:DIG:k_window 0.20
#caput GLBL:DIG:d2_window 0.30
caput GLBL:DIG:m_window 3.5
caput GLBL:DIG:CFD_fraction 30

caput GLBL:DIG:peak_sensitivity 3

caput GLBL:DIG:channel_enable 1

caput GLBL:DIG:pileup_mode 0
caput GLBL:DIG:trigger_polarity 1
caput GLBL:DIG:dropped_event_count_mode 0
caput GLBL:DIG:event_count_mode 0
caput GLBL:DIG:ahit_count_mode 0
caput GLBL:DIG:disc_count_mode 0
caput GLBL:DIG:event_extention_mode 0
caput GLBL:DIG:pileup_extention_mode 0
caput GLBL:DIG:counter_reset 0

caput GLBL:DIG:holdoff_time 140
caput GLBL:DIG:preamp_reset_delay_en Enabled
caput GLBL:DIG:preamp_reset_delay 10
caput GLBL:DIG:tracking_speed 3

caput DigFIFOSpeed Fast

echo "global settings to all digitizers done"

echo "done setting individual channels of digitizers"

echo "setting digitizer mode to TTCS everywhere"

caput GLBL:DIG:trigger_mux_select 2

#need to really put .4 for 400 ns? need to fix equation...
#caput GLBL:DIG:disc_width 1.9


# clear FIFOs to insure no old events
caput GLBL:DIG:master_fifo_reset 1 > null
caput GLBL:DIG:master_fifo_reset 0 > null

## BUG BUG BUG ##
# PV that set the load delays bit does not seem to work.
echo "loading buffer delays"

caput GLBL:DIG:load_delays 0
sleep 0.1
caput GLBL:DIG:load_delays 1
sleep 0.1
caput GLBL:DIG:load_delays 0


##################################################################
#   With system linked up, now set DGS-specific X-plane and Y-plane
#   mapping register values
##################################################################
echo "loading X-plane and Y-plane maps -- sets bgo as X-plane and ge as Y-Plane"
##In all Routers, load the X-plane with 0x1F (31) and the Y-plane with 0x3E0 (992)
for a in 1 2 3
do # fill X-plane of routers with all 31
  for b in A B C D E F G H
  do
    caput VME32:RTR"$a":reg_X_PLANE_MAP_"$b" 31 
    caput VME32:RTR"$a":reg_Y_PLANE_MAP_"$b" 992 
  done
done


# make sure SYNC on link L of Routers is removed
caput VME32:RTR1:LRUCtl02 OFF > null
caput VME32:RTR2:LRUCtl02 OFF > null
caput VME32:RTR3:LRUCtl02 OFF > null

# finish globals

caput GLBL:DIG:counter_mode 1
caput GLBL:DIG:master_counter_enable 1
caput GLBL:DIG:master_counter_reset 0

caput GLBL:DIG:master_logic_enable 0
caput GLBL:DIG:master_fifo_reset 1

caput GLBL:DIG:master_fifo_reset 0

caput GLBL:DAQ:DAQTimeDelayA 0.001
caput GLBL:DAQ:DAQTimeDelayB 0.01
caput GLBL:DAQ:BuildSendDelay 0.0

# disable slave digitizers - leave this in on default
VME="1 2 3 4 5 6 7 8 9 10 11"
for a in $VME
do
  caput DAQB"$a"_2_CS_Ena Disable
  caput DAQB"$a"_4_CS_Ena Disable
done

# This is DGS specific

# To get good suppression, need to set bgo threshold to around 23.
echo 'Setting BGO thresholds to 23'
/global/devel/systems/edm/scripts/set_bgos led_threshold 23 > null
# Not sure this is necessary but make sure BGO pileup mode is in accept
echo 'Set BGO pileup to Accept mode'
/global/devel/systems/edm/scripts/set_bgos pileup_mode Accept > null
# set baseline at zero volts for bgo
echo 'Set BGO baselines to 8192'
/global/devel/systems/edm/scripts/set_bgos baseline_start 8192  > null  # this is really 0 volts
# this appears to be necessary
echo 'Set counter_mode to one for all digitiers'
/global/devel/systems/edm/scripts/set_dig_all counter_mode 0 > null

# leave trigger in Any Ge singles

caput VME32:MTRG:XTHRESH 255
caput VME32:MTRG:YTHRESH 0
caput VME32:MTRG:SUM_Y on

caput VME32:RTR1:ENBL_DISCBIT_DELAY On
caput VME32:RTR2:ENBL_DISCBIT_DELAY On
caput VME32:RTR3:ENBL_DISCBIT_DELAY On

# current_status_DGS.save

echo "dig_dgssetup_default script is finished!!!!!!"

