#!/bin/bash -l
#!/bin/bash -l
#Saving Globals #1
caput CryG_CS_PZEna enabled
caput CryG_CS_BRE disabled
caput CryG_CS_Pol Positive
caput CryG_CS_PUE notify
caput CryG_CS_Dbg normal
caput CryG_CS_TM Internal
caput CryG_CS_PZTrace Raw
caput CryG_CS_PZMult 1550
caput CryG_CS_LEDTh 30
caput CryG_CS_RDDly 0
caput CryG_CS_RDLen 0.16
caput CryG_CS_CFDDly 630
caput CryG_CS_CFDThr 160
caput CryG_CS_CFDFrac 1/2
caput DigG_CS_ExtWin 2047
caput DigG_CS_NoiseWin 0.8
caput DigG_CS_PileWin 10
caput DigG_CS_TrigDly 0
caput DigG_CS_LRCollTime 0.8
caput DigG_CS_IntTime 4
caput DigG_CS_CollTime 0.8
caput DigG_CS_LRIntTime 4
caput DigG_CS_BaseRes 500
caput DigG_CS_AuxIOMux Debug
caput DigG_CS_DCMReset Normal
#Saving Globals #2
sleep 2
caput CryG_CS_PZEna enabled
caput CryG_CS_BRE disabled
caput CryG_CS_Pol Positive
caput CryG_CS_PUE notify
caput CryG_CS_Dbg normal
caput CryG_CS_TM Internal
caput CryG_CS_PZTrace Raw
caput CryG_CS_PZMult 1550
caput CryG_CS_LEDTh 30
caput CryG_CS_RDDly 0
caput CryG_CS_RDLen 0.16
caput CryG_CS_CFDDly 630
caput CryG_CS_CFDThr 160
caput CryG_CS_CFDFrac 1/2
caput DigG_CS_ExtWin 2047
caput DigG_CS_NoiseWin 0.8
caput DigG_CS_PileWin 10
caput DigG_CS_TrigDly 0
caput DigG_CS_LRCollTime 0.8
caput DigG_CS_IntTime 4
caput DigG_CS_CollTime 0.8
caput DigG_CS_LRIntTime 4
caput DigG_CS_BaseRes 500
caput DigG_CS_AuxIOMux Debug
caput DigG_CS_DCMReset Normal

caput CryG_CS_PZMult 0
sleep 1
caput CryG_CS_PZMult 2500
echo "all done"

