#!/bin/bash -l
sdirname="saves"
fname="array_saved_threshold"
fdate=`date +%Y-%m-%d.%H-%M`
sfile=$sdirname/$fname.$fdate

echo '#!/bin/bash -l' > $sfile
chmod +x $sfile

echo "########## Saving Global Threshold ##########"

GLBL="GLBL:DIG:led_threshold"

#echo "#Saving Global Threshold" >> $sfile
#caget $GLBL | awk '{print "caput " $1 " " $2}' >> $sfile

echo "########## Saving Individual Thresholds ##########"
echo "#Saving Individual Thresholds" >> $sfile

VME="01 02 03 04"
DIG="1 2 3 4"
CH="0 1 2 3 4 5 6 7 8 9"

PVS="led_threshold channel_enable trigger_polarity raw_data_window k0_window"

for a in $VME
do
  for b in $DIG
  do
    for c in $PVS
    do
      for d in $CH
      do 
        pv=VME"$a":MDIG"$b":"$c""$d"
        chpv=$(caget "$pv"_RBV | awk '{print $2}')
	echo $pv $chpv
        echo 'caput' $pv $chpv >> $sfile
      done
    done
  done
done

date +%m/%d/%Y-%k:%M | awk '{print "#Save Finished "$1 $2}' >> $sfile

rm -rf edm/scripts/array_saved
ln -s ../../$sfile edm/scripts/array_saved
echo "saved in : ${sfile}"
echo "########## Done Saving Thresholds ###########"
exit

