#!/bin/bash -l
sdirname="saves"
fname="array_saved_trace_length"
fdate=`date +%Y-%m-%d.%H-%M`
sfile=$sdirname/$fname.$fdate

echo '#!/bin/bash -l' > $sfile
chmod +x $sfile

echo "########## Saving Global Trace Length ##########"

GLBL="GLBL:DIG:raw_data_window"

echo "#Saving Global Trace Length" >> $sfile
caget $GLBL | awk '{print "caput " $1 " " $2}' >> $sfile

echo "########## Saving Individual Trace Length ##########"
echo "#Saving Individual Trace Length" >> $sfile

VME="01 02 03 04"
DIG="1 2 3 4"
CH="0 1 2 3 4 5 6 7 8 9"

PVS="raw_data_window"

for a in $VME
do
  for b in $DIG
  do
    for c in $PVS
    do
      for d in $CH
      do 
        pv=VME"$a":MDIG"$b":"$c""$d"
        chpv=$(caget "$pv"_RBV | awk '{print $2}')
        echo 'caput' $pv $chpv >> $sfile
      done
    done
  done
done

date +%m/%d/%Y-%k:%M | awk '{print "#Save Finished "$1 $2}' >> $sfile
echo "########## Done Saving Trace Length ###########"
rm -rf edm/scripts/array_raw_data_windows_saved
ln -s ../../$sfile edm/scripts/array_raw_data_windows_saved

exit

