#!/bin/bash -l

# This script sets d,k,m and d2 for BGO detectors.

VME="01 02 03 04 05"
DIG="MDIG1 MDIG2 MDIG3 MDIG4"

b=10

if [ ! $2 ]
then 	# -n tests to see if the argument is non empty
	echo 'Must specify PV Name and value e.g. led_threshold 25'
    exit 1
fi

for a in $VME
do  
  for b in $DIG
  do
    caput VME"$a":"$b":"$1" "$2"
 done
done

#caput VME10:MDIG1:"$1" "$2"

exit

