#!/bin/bash -l
#location=/home/helios/experiments/array/daq
location="$(pwd)"
runEdm() {
  export EDMOBJECTS=/global/devel/extensions/dgs1/src/edm/setup
  export EDMHELPFILES=/global/devel/extensions/dgs1/src/edm/helpFiles
  export EDMBASE=/global/devel/extensions/dgs1/src/edm
  export EDM=/global/devel/extensions/dgs1/src/edm/edmMain/O.linux-x86/edm
  export EDMPVOBJECTS=/global/devel/extensions/dgs1/src/edm/setup
  export EDMFILES=${location}/edm/setup
  export EDMDATAFILES=$EDMDATAFILES:${location}/edm/screens
  export EDMDATAFILES=$EDMDATAFILES:/global/devel/systems/edm/screens
  export EDMSCRIPTS=${location}/edm/scripts
  $EDM -x HELIOSMain.edl &
  echo "Edits are possible in this mode."
}
runEdm
