#!/bin/bash

if [ $# -eq 0 ] || [ $# -eq 1 ] || [ $1 == "-help"  ]; then
  echo "$./process_MultiRuns [RunNum1] [RunNum2] [Merge] [EventBuild] [GeneralSort]"
  echo "    RunNum1 = start run number"
  echo "    RunNum2 = stop run number"
  echo "      Merge =   1/0*     "  
  echo "   EventBld = 2/1/0*   || 2 = with Trace"  
  echo " GenralSort = n/1/0*   || 1 = GeneralSort.C, n = GeneralSortTraceProof.C with n-worker"
  echo "        * negative option = force "
  exit 1
fi;

source ./process_PathSetting

RUN1=$1
RUN2=$2

isMerge=1
isSort=1
isGeneralSort=1
isMonitor=1

if [ $# -ge 3 ]; then isMerge=$3; fi
if [ $# -ge 4 ]; then isSort=$4; fi
if [ $# -ge 5 ]; then isGeneralSort=$5; fi

GEBSort=GEBSort_nogeb
GEBSortMsg="using GEBSort_nogeb"
GeneralSortMsg="no trace"

if [ ${isGeneralSort} -ge 2 ] || [ ${isGeneralSort} -le -2 ] || [ $isSort -gt 1 ] || [ $isSort -lt -1 ]; then
  isTrace=1
  GEBSortMsg="using GEBSort_nogeb_trace"
  GEBSort=GEBSort_nogeb_trace
  GeneralSortMsg="trace with ${isGeneralSort} core"
fi

echo "============================================="
echo "============= RUN $RUN1 to $RUN2 ================"
echo "============================================="
echo "Merge       : ${isMerge}"
echo "Sort        : ${isSort}  ${GEBSortMsg}"  
echo "GeneralSort : ${isGeneralSort} ${GeneralSortMsg}"
echo "============================================="

if [ "${RUN1:0:1}" == "0" ]; then
    RUN1=${RUN1:1:2}
else
    RUN1=$(printf '%d' $RUN1)
fi

if [ "${RUN2:0:1}" == "0" ]; then
    RUN2=${RUN2:1:2}
else
    RUN2=$(printf '%d' $RUN2)
fi

for iRUN in $(seq ${RUN1} ${RUN2}); do

    runID=$(printf '%03d' $iRUN)

    echo -e "${Cyan}"
    echo "========================================================="
    echo "============ RUN $runID ===================================="
    echo "========================================================="
    echo -e "${NC}"

    #######################################
    ####################  Download raw data
    ./process_Download $iRUN

    #######################################
    #################### Merge
    ./process_Merge $iRUN $isMerge

    #######################################
    #################### Sort and GeneralSort
    ./process_Sort $iRUN $isSort $isGeneralSort

done

#root -l ../Armory/runsCheck.C  #check the run Entries, and duration

exit 1
